[package]
name = "shiny_reverse_proxy"
version = "0.1.0"
edition = "2024"

[lib]
name = "proxy_library"
path="src/lib.rs"


[[bin]]
name = "proxy"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0" , features = ["derive"]}
tokio = {version = "1.51.1", features = ["full"]}
reqwest = "0.13.2"
thiserror = "2.0.18"

[dev-dependencies]
predicates = "3.1.4"
assert_cmd = "2.2.0"

